### ISSUE TITLE
test server by making concurrent requests to it

### ISSUE THREAD

**Issue by madhukar93** [ameydev/kv-svc#1]
server might handle concurrency, but does the data store handle it? You can test it via something like https://httpd.apache.org/docs/2.4/programs/ab.html

**Comment by ameydev** [comment]
Now the datastore also supports concurrent read/write operations. Actually, golang Map does support concurrent read operations however it fails to perform multiple write operations unless there is a sync between the go-routines. [This](https://github.com/ameydev/kv-svc/commit/69b9206b1c73c2e5ddacd0a8f4d25a8d190a752d) is what was required.
Have tested up to 10000 successful concurrent requests on all the endpoints.

**Comment by madhukar93** [comment]
looks good now 👍🏽
